# nixpacks.toml

# Use the [providers] table to define language versions and extensions
[providers]
php = "8.1"  # Be explicit with the PHP version
node = "18" # Specify a Node.js LTS version to ensure npm is available

# Define PHP extensions here in a clean, Nixpacks-native way
[php.extensions]
gd = "*"
intl = "*"
curl = "*"
mysqli = "*" # Use mysqli, the modern extension for MySQL

# The build phase remains the same
[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

# The start phase and webServer config are also correct from before
[start]
cmd = "php-fpm -D && nginx -g 'daemon off;'"

[webServer]
command = "nginx"
config = """
server {
    listen 80;
    server_name localhost;
    root /app; # The root directory of your application in the container
    index index.php;

    # Add headers to serve security related headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval';" always;
    
    # Prevent access to dot-files, which we don't need anyway
    location ~ /\\. {
        deny all;
    }

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    location ~ \\.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
"""